### ISSUE TITLE
Implement setting of FP password

### ISSUE THREAD

**Issue by loongyh** [loongyh/esphome-fingerprint#1]
1. Setting from yaml
2. Setting from an action

**Comment by loongyh** [comment]
@OnFreund Do you think this should be exposed as an action? Since setting a different password will mean the user will have to reconfigure the component in the config .yaml anyway to define the new password, maybe it makes more sense to be just a temporary `set_password:` .yaml config option the user is supposed to flash and run once then remove and define the newly set password under the `password:` option.

**Comment by OnFreund** [comment]
yeah, I completely agree
