### ISSUE TITLE
Implement LED Control

### ISSUE THREAD

**Issue by OnFreund** [loongyh/esphome-fingerprint#3]
What's the right API here? Should it be a light? Maybe 3 lights (for the 3 colors)? Or maybe just an action?

**Comment by loongyh** [comment]
If I read the datasheet correctly, there are 2 LEDs, one blue, one red right? purple is just those two leds turned on. Not sure if the module is capable of dimming, if it's just on/off then output will do.

**Comment by OnFreund** [comment]
I don't know how many leds there are physically, but you can choose between the 3 colors, and you can create all sorts of patterns and effects (breathing, flashing, control number of loops, etc...) You can check out instruction AuraLedConfig (0x35) in the user manual.

**Comment by loongyh** [comment]
Oh yes those effects.. Anyway I don't think that should be a light component as imo light components are in the context of lighting, indicators are more like internal output components.
i'm thinking we should expose each of those flashy effects as actions instead so the user can configure them in the yaml as automation actions.

**Comment by OnFreund** [comment]
Just so we have the information handy, these are the inputs when controlling the leds (all inputs are 1 byte in size):
* Control - one of:
  * Breathing (0x01)
  * Flashing (0x02)
  * Always on (0x03)
  * Always off (0x04)
  * Gradually on (0x05)
  * Gradually off (0x06)
* Color - one of:
  * Red (0x01)
  * Blue (0x02)
  * Purple (0x03)
* Speed (relevant for breathing, flashing and gradually *) - a number between 0 and 255
* Count (only relevant for breathing and flashing)- how many times to repeat the pattern. 0 for infinite, or 1-255.

I've found that single count flashing, with a speed of 200 to be very useful for indication, as it sets the led to the specified color for a few seconds and then turns it off.

**Comment by loongyh** [comment]
We are using the adafruit lib for now right? Just till we get the core component functions up.
`uint8_t LEDcontrol(bool on);`
`uint8_t LEDcontrol(uint8_t control, uint8_t speed, uint8_t coloridx,
                     uint8_t count = 0);`
Code for LED control will be along the line of `finger_->LEDcontrol(true)`

**Comment by OnFreund** [comment]
> We are using the adafruit lib for now right? Just till we get the core component functions up.

I believe we should. An example call:
```
finger_->LEDcontrol(FINGERPRINT_LED_FLASHING, 200, FINGERPRINT_LED_BLUE, 1);
```
