### ISSUE TITLE
Make sensing_pin optional

### ISSUE THREAD

**Issue by loongyh** [loongyh/esphome-fingerprint#5]
@OnFreund Some Rxxx models like the [optical one from adafruit](https://learn.adafruit.com/adafruit-optical-fingerprint-sensor/enrolling-new-users-with-windows) does not have a sensing pin.

**Comment by OnFreund** [comment]
The link actually shows that it does (either the blue or yellow wire - one of them is Vin for sensing, and the other is NC).
In any case, you can always point at a low pin and everything will work the same - it will simply call the reader to get an image on every loop.

**Comment by loongyh** [comment]
| Pin | Name         | Description                               |
| --- | ------------ | ----------------------------------------- |
| 1   | Power Supply | DC3.3V                                    |
| 2   | GND          | Signal ground. Connected to power ground. |
| 3   | TXD          | Data output. TTL logical level            |
| 4   | RXD          | Data input. TTL logical level             |
| 5   | WAKEUP       | Finger Detection Signal                   |
| 6   | 3.3VT        | Touch induction power supply, DC3—6V      |

3.3VT has to be connected for WAKEUP to work? I tried connecting just WAKEUP, it's HIGH and did go LOW when finger is present.

**Comment by OnFreund** [comment]
Interesting. For me it only works when 3.3VT is connected.

**Comment by loongyh** [comment]
Maybe for mine it's already internally connected to Vcc. 3.3VT seems redundant when power can be just tapped directly from Vcc.

**Comment by OnFreund** [comment]
Yeah, I think it might be useful if you want a different voltage there. In any case, shouldn't affect the software in any way.
