### ISSUE TITLE
Initial fix

### ISSUE THREAD

**Issue by loongyh** [loongyh/esphome-fingerprint#7]
@OnFreund made a bunch of fixes and got it to compile successfully. Merged into [dev branch](https://github.com/loongyh/esphome-fingerprint/tree/dev), can you review?

**Comment by OnFreund** [comment]
Looked over it and it looks great, but I do have some minor comments (mainly stuff that could be unsigned).
Can you open a PR - I think it'll be easier to discuss that way.
Also, while it compiles, I'm assuming this isn't working yet, since `finger_` isn't being initialized anywhere.

**Comment by loongyh** [comment]
@OnFreund 

> mainly stuff that could be unsigned

Just in time :) Pushed the changes to uints, except `int finger_id = -1;` in `RxxxComponent::scan_and_match()` which I'm unsure if we can just initialize it as uint16_t without assignment, since if I'm not mistaken it won't be used anyway if result != FINGERPRINT_OK.

> Can you open a PR

Done

> since finger_ isn't being initialized anywhere

I'm not sure if we can import in libs from outside of platformio. Thus unsure how to go about using your forked lib with the stream add-on. Perhaps you can PR adafruit and see if they're open to adding in a stream constructor, may be a useful addition for others even outside ESPHome.
